### ISSUE TITLE
unforeseen consequences

### ISSUE THREAD

**Issue by jvyden** [rosenishere/the-hacker-program#4]

**Comment by Daniel7689** [comment]
Shut up nigger stop bullying him go back to your oldsu shithole before I beat the shit out of you

**Comment by rosenishere** [comment]
Hi what the fuck is happening here?

**Comment by rosenishere** [comment]
how old are u jvyden

**Comment by jvyden** [comment]
considering it matters to you, i'd guess you're 13?

**Comment by rosenishere** [comment]
no next question do u like water

**Comment by jvyden** [comment]
i dont take questions from small children

**Comment by jvyden** [comment]
please be older than 13 and ask again

**Comment by rosenishere** [comment]
ok dude you’re supposed to be harassing me but u cant even answer one question I’m closing this

**Comment by jvyden** [comment]
the child is mad

**Comment by rosenishere** [comment]
cant drink my water man

**Comment by rosenishere** [comment]
hi did ur opinion on water change yet

**Comment by rosenishere** [comment]
it’s a yes or no question
